name: Build

on: [ workflow_dispatch ]

env:
  APP_VERSION: '0.2.0'

jobs:
  build-win-x64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - name: Build Windows
        run: npm run build
      - name: Package Windows
        run: npm run pack-win
      - name: Upload Artifact - Windows
        uses: actions/upload-artifact@v4
        with:
          name: m3u8downloader-v${{ env.APP_VERSION }}-win32-x64.zip
          path: release/m3u8downloader-v${{ env.APP_VERSION }}-win32-x64.zip
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac-x64:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - name: Build MacOS
        run: npm run build
      - name: Package MacOS
        run: npm run pack-mac
      - name: Upload Artifact - MacOS
        uses: actions/upload-artifact@v4
        with:
          name: m3u8downloader-v${{ env.APP_VERSION }}-darwin-x64.dmg
          path: release/m3u8downloader-v${{ env.APP_VERSION }}-darwin-x64.dmg
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux-x64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - name: Build Linux
        run: npm run build
      - name: Package Linux
        run: npm run pack-linux
      - name: Upload Artifact - Linux
        uses: actions/upload-artifact@v4
        with:
          name: m3u8downloader-v${{ env.APP_VERSION }}-linux-x64.tar.gz
          path: release/m3u8downloader-v${{ env.APP_VERSION }}-linux-x64.tar.gz
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
