name: Release

on: workflow_dispatch

env:
  APP_VERSION: '0.2.0'

jobs:
  build-win-x64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - name: Build Windows
        run: npm run build
      - name: Package Windows
        run: npm run pack-win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Artifact - Windows
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ env.APP_VERSION }}
          files: |
            release/m3u8downloader-v${{ env.APP_VERSION }}-win32-x64.zip

  build-mac-x64:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - name: Build MacOS
        run: npm run build
      - name: Package MacOS
        run: npm run pack-mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Artifact - MacOS
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ env.APP_VERSION }}
          files: |
            release/m3u8downloader-v${{ env.APP_VERSION }}-darwin-x64.dmg

  build-linux-x64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - name: Build Linux
        run: npm run build
      - name: Package Linux
        run: npm run pack-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Artifact - Linux
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ env.APP_VERSION }}
          files: |
            release/m3u8downloader-v${{ env.APP_VERSION }}-linux-x64.tar.gz
